---
title: "Developing Data Products"
author: "Piotr Zalewski"
date: "11/4/2021"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## `mtcars` dataset

### Description

*The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models).*  

### Usage

`mtcars`

## `mtcars` dataset, contd.

### Format

*A data frame with 32 observations on 11 (numeric) variables.*  

[, 1]	**mpg**	Miles/(US) gallon  
[, 2]	**cyl**	Number of cylinders  
[, 3]	**disp**	Displacement (cu.in.)  
[, 4]	**hp**	Gross horsepower  
[, 5]	**drat**	Rear axle ratio  
[, 6]	**wt**	Weight (1000 lbs)  
[, 7]	**qsec**	1/4 mile time  
[, 8]	**vs**	Engine (0 = V-shaped, 1 = straight)  
[, 9]	**am**	Transmission (0 = automatic, 1 = manual)  
[,10]	**gear**	Number of forward gears  
[,11]	**carb**	Number of carburetors  

## Sample 3D Plot

You can explore `mtcars` dataset in the interactive chart.  
```{r, comment="", message=FALSE, echo=FALSE}
library(plotly)
library(datasets)
data(mtcars)
mtcars %>%
  plot_ly(x = ~wt,
          y = ~mpg,
          z = ~hp,
          color = ~disp,
          colors = "Oranges",
          type = "scatter3d",
          mode = "markers")
```
